/* Formatted on 19.08.2022 12:21:03 (QP5 v5.277) */
--left

SELECT P.T_CHANGE_DATE, PE.T_OPER
  FROM DPARTY_DBT P LEFT JOIN DPERSON_DBT PE ON P.T_PARTYID = PE.T_PARTYID
 WHERE T_CHANGE_DATE > TO_DATE ('01.01.2021', 'dd.mm.yyyy');

SELECT P.T_CHANGE_DATE, PE.T_OPER
  FROM DPARTY_DBT P, DPERSON_DBT PE
 WHERE     T_CHANGE_DATE > TO_DATE ('01.01.2021', 'dd.mm.yyyy')
       AND P.T_PARTYID = PE.T_PARTYID(+);


SELECT P.T_PARTYID, REPLACE (PE.T_ISEMPLOYER, CHR (0), 'not IP') FORM
  FROM DPARTY_DBT P LEFT JOIN DPERSN_DBT PE ON P.T_PARTYID = PE.T_PERSONID;

--right

SELECT P.T_CHANGE_DATE, PE.T_OPER
  FROM DPARTY_DBT P RIGHT JOIN DPERSON_DBT PE ON P.T_PARTYID = PE.T_PARTYID;

SELECT P.T_CHANGE_DATE, PE.T_OPER
  FROM DPARTY_DBT P, DPERSON_DBT PE
 WHERE P.T_PARTYID(+) = PE.T_PARTYID;


SELECT P.T_PARTYID, REPLACE (PE.T_ISEMPLOYER, CHR (0), 'not IP') FORM
  FROM DPARTY_DBT P RIGHT JOIN DPERSN_DBT PE ON P.T_PARTYID = PE.T_PERSONID;

--inner

SELECT P.T_CHANGE_DATE, PE.T_OPER
  FROM DPARTY_DBT P JOIN DPERSON_DBT PE ON P.T_PARTYID = PE.T_PARTYID
 WHERE T_CHANGE_DATE > TO_DATE ('01.01.2021', 'dd.mm.yyyy');

SELECT P.T_CHANGE_DATE, PE.T_OPER
  FROM DPARTY_DBT P, DPERSON_DBT PE
 WHERE     P.T_PARTYID = PE.T_PARTYID
       AND T_CHANGE_DATE > TO_DATE ('01.01.2021', 'dd.mm.yyyy');

--outer
SELECT P.T_CHANGE_DATE, PE.T_OPER
  FROM DPARTY_DBT P FULL JOIN DPERSON_DBT PE ON P.T_PARTYID = PE.T_PARTYID;
