/* Formatted on 18.08.2022 15:19:58 (QP5 v5.277) */
--SQL FUNCTIONS

SELECT MAX (P.T_PARTYID) MAX_ID
  FROM DPARTY_DBT P;

SELECT MIN (P.T_PARTYID) AS MIN_ID
  FROM DPARTY_DBT P;

SELECT COUNT (P.T_PARTYID) AS COUNT_PARTY
  FROM DPARTY_DBT P;

SELECT ROUND (AVG (P.T_PARTYID), 4)
  FROM DPARTY_DBT P;

SELECT CHR (88) FROM DUAL;

SELECT ASCII ('U') FROM DUAL;


SELECT P.T_SHORTNAME
  FROM DPARTY_DBT P
 WHERE LENGTH (P.T_SHORTNAME) < 10;

SELECT CURRENT_DATE FROM DUAL;

SELECT (CURRENT_DATE + 2)
  FROM DUAL;

SELECT LAST_DAY (TO_DATE ('01.08.2022', 'dd.mm.yyyy')) FROM DUAL;

SELECT NVL (P.T_OKPO, 'test')
  FROM DPARTY_DBT P
 WHERE LENGTH (P.T_OKPO) IS NULL;